apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ckb-mainnet-sync-normal
spec:
  serviceName: ckb-mainnet-sync-normal-service
  replicas: 1
  selector:
    matchLabels:
      app: ckb-mainnet-sync-normal
  template:
    metadata:
      labels:
        app: ckb-mainnet-sync-normal
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: ckb-mainnet-sync-normal
          image: registry.cn-hangzhou.aliyuncs.com/scz996/ckb:async-download-2024-04-07-5c2a089ac
          securityContext:
            privileged: true
          ports:
            - containerPort: 8114
              name: rpc
            - containerPort: 8100
              name: monitor
          command:
            - bash
            - -c
            - |
              set -ex
              cd /var/lib/ckb
              ckb init --chain mainnet --force
              
              config_content="
              [metrics.exporter.prometheus]
              target = { type = \"prometheus\", listen_address = \"0.0.0.0:8100\" }
              
              # # Experimental: Monitor memory changes.
              [memory_tracker]
              # # Seconds between checking the process, 0 is disable, default is 0.
              interval = 5
              "
              echo "$config_content" >>ckb.toml
                            
              ckb migrate --force
              ckb run --indexer
          volumeMounts:
            - name: data
              mountPath: /var/lib/ckb
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 200Gi
