apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ckb-mainnet-sync
spec:
  serviceName: ckb-mainnet-sync
  replicas: 3
  selector:
    matchLabels:
      app: ckb-mainnet-sync
  template:
    metadata:
      labels:
        app: ckb-mainnet-sync
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: ckb-mainnet-sync
          image: registry.cn-hangzhou.aliyuncs.com/scz996/ckb:async-2024-02-09-ebf6c3c05
          securityContext:
            privileged: true
          ports:
            - containerPort: 8114
              name: rpc
            - containerPort: 8100
              name: monitor
          command:
            - bash
            - -c
            - |
              set -ex
              cd /var/lib/ckb
              ckb init --chain mainnet --force
              ckb migrate --force
              ckb run --indexer
          volumeMounts:
            - name: data
              mountPath: /var/lib/ckb
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 200Gi
