apiVersion: batch/v1
kind: CronJob
metadata:
  name: ckb-number-fetcher-cron
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ckb-number-fetcher
              image: registry.cn-hangzhou.aliyuncs.com/scz996/network-tools:latest
              command: ["/bin/bash", "-c"]
              args:
                - |
                  num=3
                  for i in $(seq 0 $((num - 1))); do
                    hex_number=$(curl -sS -X POST -H "Content-Type: application/json" -d '{"id": 1, "jsonrpc": "2.0", "method": "get_tip_header", "params": []}' http://ckb-mainnet-sync-$i.ckb-mainnet-sync-service.ckb-mainnet-sync.svc:8114 | jq -r '.result.number' | sed 's/^0x//')
                    if [[ $? -ne 0 || -z "$hex_number" ]]; then
                      node_numbers[$i]="获取失败"
                    else
                      node_numbers[$i]=$((16#$hex_number))
                    fi
                  done
                  echo "$(date "+%Y-%m-%d %H:%M:%S") ${node_numbers[*]}"
          restartPolicy: OnFailure
