apiVersion: v1
kind: Service
metadata:
  name: ckb-mainnet-sync-base-service
  labels:
    app: ckb-mainnet-sync-base
spec:
  ports:
    - port: 8114
      targetPort: 8114
      name: rpc
  clusterIP: None
  selector:
    app: ckb-mainnet-sync-base
