apiVersion: v1
kind: Service
metadata:
  name: ckb-mainnet-sync-normal-service
  namespace: ckb-mainnet-sync
  labels:
    app: ckb-mainnet-sync-normal
spec:
  ports:
    - name: rpc
      protocol: TCP
      port: 8114
      targetPort: 8114
    - name: monitor
      protocol: TCP
      port: 8100
      targetPort: 8100
  selector:
    app: ckb-mainnet-sync-normal
